---
- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
  tags: packages

- name: Install newrelic
  pip: name=newrelic
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages
